### ISSUE TITLE
How to pass the confirm/cancel button result to the component?

### ISSUE THREAD

**Issue by theonecf** [czeckd/angular-basic-modal#14]
Right now, if the users click confirm/cancel button on the modal, it just  close the modal. How can it pass any result back to the component? so the component can perform any actions based upon confirm/cancel.

Please help.!

**Comment by czeckd** [comment]
The demo app has an example of how to do this. From line 255 in `demo-app.component.ts`:

`this.modal.show().then( (res:string) => this.result = res);`

The modal returns a promise. The promise resolves to a string that gives the name of the button clicked.

To see it in action, look at the [demo](http://czeckd.github.io/angular2-simple-modal/demo/) and check the "show result" option.
