### ISSUE TITLE
Apply modal to a form

### ISSUE THREAD

**Issue by paulocoutinhox** [czeckd/angular-basic-modal#16]
Hi,

I want know if i can use it to show my form inside modal.

On this line i show the form, a dynamic form:
https://github.com/prsolucoes/goci/blob/support-angular2/resources/web-app/app/project-view/project-view.component.ts#L99

But it shows on HTML, hiding one div and showing the form div that is my component called TaskOptions:
https://github.com/prsolucoes/goci/tree/support-angular2/resources/web-app/app/task-options

Can you help me? I use your component with success with string modal content like in examples.

**Comment by czeckd** [comment]
What I would do to display a form in a simple-modal would be to make the form a component and then use that component in a new template to pass to the modal. So, something like this example --  `demo-form.component.ts`:

```
import { Component } from '@angular/core';

@Component({
  selector: 'demo-form',
  template: '<form><input type="text" [(ngModel)]="message" name="msg"></form>'
})
export class DemoFormComponent {
  private message:string;
}
```

Then make a custom template, such as this example using the demo's css:

```
private formTemplate:string = `
<div class="modal-background" (click)="dismiss()">
  <div class="modal" (click)="$event.stopPropagation()" [ngStyle]="{'width': width + 'px', 'height':  height + 'px'}">
    <demo-form></demo-form>
    <div class="modal-buttonbar">
      <button *ngIf="cancelBtn" (click)="cancel()" >{{cancelBtn}}</button>
    </div>
  </div>
</div>`;
```

Notice that this new modal template is using the `<demo-form>` component instead of the title, and message, and other parameters on simple-modal.

Then before calling the modal, assign this template to it. So, changing the `showModal()` in `demo-app.component.ts` to something like:

```
showModal() {
  this.result = null;
  this.confirmText();
  this.cancelText();
  this.modal.template = this.formTemplate;
  this.modal.show().then( (res:string) => this.result = res);
}
```

**Comment by paulocoutinhox** [comment]
Hi,

The problem is that my component, it receives a lot of inputs:

<task-options *ngIf="showTaskOptionsForm" [projectId]="runProjectId" [projectName]="runProjectName" [taskId]="runTaskId" [taskName]="runTaskName" [taskDescription]="runTaskDescription" [options]="runTaskOptions" (taskRunWithSuccess)="taskRunWithSuccess($event)" (taskRunWithError)="taskRunWithError($event)" (taskRunCancel)="taskRunCancel($event)"></task-options>

How i can pass the input params to it?

Thanks.

**Comment by czeckd** [comment]
You could extend simple-modal to take more inputs, but really that is overkill for what it seems you need.

Looking at your project, I think I **would not** use the simple-modal at all for this use case. Instead, I would just make a modal inline in the template on [task-view.component.html](https://github.com/prsolucoes/goci/blob/support-angular2/resources/web-app/app/task-view/task-view.component.html) and use `*ngIf` to control the display. So, I would code something like the following change, beginning at line 170:

```
<div *ngIf="showTaskOptionsForm" class="modal-background" (click)="dismiss()">
  <div class="modal" (click)="$event.stopPropagation()">
    <task-options  [projectId]="runProjectId" [projectName]="runProjectName"
         [taskId]="runTaskId" [taskName]="runTaskName" [taskDescription]="runTaskDescription"
         [options]="runTaskOptions" (taskRunWithSuccess)="taskRunWithSuccess($event)"
         (taskRunWithError)="taskRunWithError($event)" (taskRunCancel)="taskRunCancel($event)">         
    </task-options>
    <button (click)="showTaskOptionsForm=false" >Close</button>
  </div>
</div>
```

I would borrow the css I used in simple-modal for [task-view.component.css](https://github.com/prsolucoes/goci/blob/support-angular2/resources/web-app/app/task-view/task-view.component.css).

```
.modal {
    position: fixed;
    border: 2px solid #eee;
    border-radius: 4px;
    background-color: #fff;
    padding:15px;   
    left:50%; 
    top:35%;
    -webkit-transform: translate(-50%, -50%);
    -moz-transform: translate(-50%, -50%);
    -ms-transform: translate(-50%, -50%);
    -o-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
}

.modal-background {
    position:fixed; 
    background-color: rgba(0,0,0,0.5);
    left:0; 
    top:0;
    width:100%; 
    height:100%;
}
```

In my own applications, I use a mix of modal approaches depending on the use case. For more complex modals, I do the above approach. For alerts, or confirmations, I use simple-modal.

**Comment by paulocoutinhox** [comment]
Yes, is what i do:
https://github.com/prsolucoes/goci/blob/support-angular2/resources/web-app/app/task-options/task-options.component.html

I copy and modify the CSS from: 
http://www.w3schools.com/howto/howto_css_modals.asp

But thanks :)

**Comment by czeckd** [comment]
With rc.6 removing depreciated functionality from Angular 2, I needed to refactor the modal to make it work. I added a `BaseModalConfig` that could be extended to pass the input params needed to a form.
