### ISSUE TITLE
 "export 'BaseModalConfig' was not found in 'angular-basic-modal'

### ISSUE THREAD

**Issue by webmatrixxxl** [czeckd/angular-basic-modal#33]
https://cl.ly/252A130m370X
import { BaseModalConfig, BaseModal, BasicModalService } from 'angular-basic-modal';

WARNING in ./src/app/modal/modal.component.ts
22:23-38 "export 'BaseModalConfig' was not found in 'angular-basic-modal'

WARNING in ./src/app/modal/modal.component.ts
35:40-49 "export 'BaseModal' was not found in 'angular-basic-modal'

WARNING in ./src/app/modal/modal.component.ts
66:57-74 "export 'BasicModalService' was not found in 'angular-basic-modal'

WARNING in ./src/app/modal/modal.component.ts
66:94-111 "export 'BasicModalService' was not found in 'angular-basic-modal'

angular/cli: 1.1.1
node: 7.7.4
os: darwin x64
angular/common: 4.2.3
angular/compiler: 4.2.3
angular/core: 4.2.3
angular/forms: 4.2.3
angular/http: 4.2.3
angular/platform-browser: 4.2.3
angular/platform-browser-dynamic: 4.2.3
angular/router: 4.2.3
angular/cli: 1.1.1
angular/compiler-cli: 4.2.3

**Comment by czeckd** [comment]
Try:
```typescript
import { BaseModalConfig, BaseModal, BasicModalService } from 'angular-basic-modal/index';
```

See if that makes a difference with 4.2.3.
