### ISSUE TITLE
Can use cancel on background overlay

### ISSUE THREAD

**Issue by shaildyp** [czeckd/angular-basic-modal#4]
```
    let template:string = this.template + '<div class="modal-background" (click)="cancel()"></div>';
    /*let template:string = `<div (click)="$event.stopPropagation()">`+
     this.template +
     `</div>
     <div class="modal-background" (click)="cancel()"></div>`*/;
```

**Comment by czeckd** [comment]
I added support for background cancel. Updated code and demo is available. Was there a use case for the commented out code you were trying?

**Comment by shaildyp** [comment]
Yes. You can use parent element as the overlay and stop the click propagation on modal's root element. In your case you are using an extra element as the background overly.

**Comment by czeckd** [comment]
Thank you. I think I correctly understood what you suggested and modified the code accordingly. Please take a look if you have a chance and let me know.

**Comment by shaildyp** [comment]
I can contribute to this repo if you want. Let me know.

**Comment by czeckd** [comment]
Up to you really. Feel free to adapt it to what works for your projects.
